general:
#  result_path: ./prover-benchmark-results/results-number-of-predicates-and-variables-prover9
#  result_path: ./prover-benchmark-results/results-number-of-functors
#  result_path: ./prover-benchmark-results/results-atom-clause-ratio
  result_path: ./prover-benchmark-results/results-negation-ratio
  result_as_json: True
  result_as_csv: True
  test_timeout: 300

translators:
  - from_format: TPTP
    to_format: LADR
    command: ../provers/LADR-2009-11A/bin/tptp_to_ladr
    input_mode: stdin
    output_mode: stdout

test_inputs:
   - name: negation_ratio
     patterns:
       - ./data-sets/_generated/_fol-tptp-cnf-negation-ratio/**/*.p
     format: TPTP
#  - name: number_of_functors
#    patterns:
#      - ./data-sets/_generated/_fol-tptp-cnf-number-of-functors/**/*.p
#    format: TPTP
#  - name: number_of_predicates_and_variables
#    patterns:
#      - ./data-sets/_generated/_fol-tptp-cnf-number-of-predicates-and-variables/**/*.p
#    format: TPTP
#  - name: atom_clause_ratio
#    patterns:
#    - ./data-sets/_generated/_fol-tptp-cnf-atom-clause-ratio/**/*.p
#    format: TPTP
#  - name: liveness_safety_ratio
#    patterns:
#      - ./data-sets/_generated/_fol-tptp-cnf-liveness-safety-ratio/**/*.p
#    format: TPTP
#  - name: k-sat
#    patterns:
#      - ./data-sets/_generated/_fol-tptp-cnf-k-sat/**/*.p
#    format: TPTP

test_suites:
  - name: Prover9 test suite
    command: ../provers/LADR-2009-11A/bin/prover9
    input_mode: stdin
    version: 2009-11A
    required_format: LADR
    save_stdout: False
    save_stderr: True
